### PR TITLE
Alternative implementation

### PR DESCRIPTION
**Pull request by ivoputzer**
here's an alternative of how things could be implemented ;) cheers

### CODE REVIEW

**Comment by christian-fei** [comment]
and the award goes to... IVO VONTZER

**Comment by ivoputzer** [comment]
not true, i just noticed that i missed out on line numbers. to add them back there's like a css rule to apply one can apply:

```
.prettyprint ol.linenums > li { list-style-type: decimal; }
```

**Comment by ivoputzer** [comment]
fixed merge conflicts ;) screw u @christian-fei

**Comment by christian-fei** [comment]
hahaa :)

**Comment by 0xNaN** [comment]
Thanks guys for the awesome work!!

**Pull request merged**
